pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "QAHarness"
include(":app")
include(":opencv")
project(":opencv").projectDir = file(providers.gradleProperty("opencvSdkDir").getOrElse("C:/OpenCV-android-sdk/sdk"))
